# Generated by Django 3.2.5 on 2021-08-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('Issue_Type', models.CharField(max_length=255)),
                ('Summary', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=255)),
                ('Application', models.CharField(max_length=255)),
            ],
        ),
    ]
