# Generated by Django 3.2.5 on 2021-08-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
