# Generated by Django 3.2.5 on 2021-08-31 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_alter_work_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='work',
            table='POC_TABLE',
        ),
    ]
