# Generated by Django 3.2.5 on 2021-08-31 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_alter_work_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='work',
            table='NEW_POC_TABLES',
        ),
    ]
