# Generated by Django 3.2.5 on 2021-08-31 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_alter_work_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='work',
            table=None,
        ),
    ]
